package com.google.cms.utilities.enums;

public enum PurchaseRequisitionEnum {
    PENDING, REJECTED, APPROVED, RETURNED,
    APPROVED_BY_HOD, APPROVED_BY_PROCUREMENT, APPROVED_BY_FINANCE,
    REJECTED_BY_HOD, REJECTED_BY_PROCUREMENT, REJECTED_BY_FINANCE,
    RETURNED_BY_HOD, RETURNED_BY_PROCUREMENT, RETURNED_BY_FINANCE,
    PO_ISSUED, PO_NOT_ISSUED
}

